### ISSUE TITLE
EPH role in private channel

### ISSUE THREAD

**Issue by Necrophote** [ewohltman/ephemeral-roles#237]
In the past, voice room in hidden/private channel (where EPH bot role (ephemeral role) aint granted access) wont be affected / given role
I appreciate this feature, which gives privacy to specific channel
Recently this has been changed, even in the channel where EPH not allowed, it still creates role and auto-manages it
Can this be undone?
Idk if this a bug or intended, but really looking for your reply
Sure it can be temp fixed by changing private role to no-color, removing it manually to remain hidden when going ninja mode in big server, but kinda annoying
Thanks for your service

**Comment by ewohltman** [comment]
Thanks for raising this issue!

Some recent changes have go in, but I'm not sure how it affected this behavior. I'll definitely look into it and see if we can put something in place to restore the previous behavior. I intend to respect my user's privacy so I agree if the bot is lacking roles to a voice channel than it should not be able to manage it either.

**Comment by ewohltman** [comment]
@Necrophote 

I've just merged a change to hopefully help with this. I'm not sure how Ephemeral Roles was able to ignore channels previously based upon roles, but I've put in an explicit check now to see if the bot's role is denied the `View Channel` voice permission. If so, it will skip applying a role for that channel.

![channel_permissions](https://user-images.githubusercontent.com/5953186/78038118-72d3c500-733a-11ea-8f76-af9cf54be034.png)

This screenshot shows an example of a voice channel's permissions where the `Ephemeral Roles` role has been denied the `View Channel` permission.

Would this work for you and could you try it out when you get a chance?

**Comment by Necrophote** [comment]
It works
I added EPH role into EACH private channel permission and cancel out "Read Text Channels and See Voice Channels", then things done
Previously, in private channels, EPH role not included = no adding roles
Now, it requires EPH role addition to be muted
Sounds manual, but it definitely a fix
Idk if it could be totally reverted back to original version (no inclusion = no permission), Im already satisfied at this point
Thank you for your hard works
If no further fix planned, could you close this issue for me?

**Comment by Necrophote** [comment]
That happens again

**Comment by Necrophote** [comment]
Excellent, now manual addition of EPH to be banned no longer required
EPH turns back to previous behavior (before the bug emerged)
Ill report if anything about to happen again

**Comment by ewohltman** [comment]
Glad to hear it! Thanks for reporting this bug and testing the fix. Please do report back if you seen unexpected behavior again.

**Comment by herrlegno** [comment]
For me, the bot is not revoking the roles after leaving the voice chat.

![image](https://user-images.githubusercontent.com/11634168/80810532-f8f25e00-8bbb-11ea-9e95-01a4619e52b7.png)

I have EPH role with "Read Text Channels and See Voice Channels" check in those voice chats.

**Comment by ewohltman** [comment]
Hey @herrlegno 

Sorry to hear about the issue you're facing! This has been an issue I've been working on for awhile, and unfortunately can result from a number of reasons including latency with Discord's API, rate limiting, etc.

I'm continuously trying to find the most resilient way to ensure the desired state (roles added and revoked) match the actual state of the world (members present in voice channels or not). Some of my plans are to hook into additional events from Discord to have more opportunities to check and rectify state, as well as more caching of information in memory for better performance.

Is this something you're seeing consistently, or does it happen intermittently when your members join/leave voice channels?

I know it's not ideal, but in the meantime could you manually revoke the roles while I continue to shore up the resiliency behind this?

**Comment by herrlegno** [comment]
Oh I see, for me this happens consistenly or it takes a really long time before the role is revoked. This matter it's not a matter of life and death for my case but it would be nice to see this feature working properly.

Thanks for your fast response, I'll be waiting gladly for the fix.

**Comment by ewohltman** [comment]
This is hopefully improved with PR https://github.com/ewohltman/ephemeral-roles/pull/262.

If the issue of automatically revoking roles is still being observed, please feel free to comment in Issue https://github.com/ewohltman/ephemeral-roles/issues/260.
